CREATE DATABASE FESTIVALS;
USE FESTIVALS;
DROP DATABASE FESTIVALS;
CREATE TABLE FESTI_INFO(
SNO INT, NAME VARCHAR(200), STATE VARCHAR(200), FAMOUS BOOLEAN, STARTDATE INT, ENDDATE INT,FOOD VARCHAR(200),RELIGION VARCHAR (300)
);

INSERT INTO FESTI_INFO (SNO,NAME,STATE,FAMOUS,STARTDATE,ENDDATE,FOOD,RELIGION)
VALUES(1,'Ganeshachathurthi','KARNATAKA',TRUE,18,28,'KUDUMU','HINDU'),(2,'Diwali','TELANGANA',True,10,20,'NONVEG','HINDU'),(3,'SRIRAMANAVAMI','A.P',TRUE,12,23,'VADAPAPPU','HINDU'),
(4,'HOLI','RAJASTHAN',TRUE,1,3,'BIRIYANI','HINDHU'),(5,'CHRISTHMAS','KERALA',TRUE,25,28,'BIRIYANI','CHRISTIANS'),(6,'RAMJAN','SRILANKA',TRUE,21,24,'PAYASAM','MUSLIMS'),(7,'BAKRIDH','U.P',FALSE,22,24,'NONVEG','MUSLIMS'),
(8,'DASARA','KARNATAKA',TRUE,23,09,'SWEETS','HINDU');

SELECT * FROM FESTI_INFO
