package driver;

import com.xworkz.september.things.Google;

public class GoogleRunner {
public static void main(String[] args) {
	Google google = new Google();
	google.setSearchQuery("wt is the definition of sql");
	google.getSearchQuery();
	String searchQuery=google.getSearchQuery();
	System.out.println(searchQuery);
	google.setSearchResults(90);
	google.getSearchResults();
	int searchResults=google.getSearchResults();
	System.out.println(searchResults);
	google.setSafeSearchEnabled(false);
	google.isSafeSearchEnabled();
	boolean safeSearch=google.isSafeSearchEnabled();
	System.out.println(safeSearch);
	google.setLanguage("telugu,english");
	google.getLanguage();
	String language=google.getLanguage();
	System.out.println(language);
	google.setAdsEnabled(true);
	google.isAdsEnabled();
	boolean isAdsEnabled=google.isAdsEnabled();
	System.out.println(isAdsEnabled);
	google.setLocation("Tirupathi");
	google.getLocation();
	String location=google.getLocation();
System.out.println(location);
google.setPersonalizedResults(true);
google.isPersonalizedResults();
boolean personalizedResult=google.isPersonalizedResults();
System.out.println(personalizedResult);
google.setVoiceSearchEnabled(false);
google.isVoiceSearchEnabled();
boolean voiceSearchEnabled=google.isVoiceSearchEnabled();
System.out.println(voiceSearchEnabled);
google.setNewsNotificationsEnabled(false);
google.isNewsNotificationsEnabled();
boolean isNewsNotification=google.isNewsNotificationsEnabled();
System.out.println(isNewsNotification);
google.setWeatherNotificationsEnabled(true);
google.isWeatherNotificationsEnabled();
boolean isWeatherNotification=google.isWeatherNotificationsEnabled();
System.out.println(isWeatherNotification);
google.setTheme("Wall paper");
google.getTheme();
String theme=google.getTheme();
System.out.println(theme);
google.setTimezone("IST");
google.getTimezone();
String TimeZone=google.getTimezone();
System.out.println(TimeZone);
google.setSaveSearchHistory(true);
google.isSaveSearchHistory();
boolean saveSearchHistory=google.isSaveSearchHistory();
System.out.println(saveSearchHistory);
google.setLocationHistoryEnabled(true);
google.isLocationHistoryEnabled();
boolean locationEnabled=google.isLocationHistoryEnabled();
System.out.println(locationEnabled);
google.setTwoFactorAuthentication(true);
google.isTwoFactorAuthentication();
boolean twoFactorAuthentication=google.isTwoFactorAuthentication();
System.out.println(twoFactorAuthentication);
google.setAccountName("shivani");
	google.getAccountName();
	String accountName=google.getAccountName();
	System.out.println(accountName);
	google.setProfilePictureUrl("https://www.youtube.com/watch?v=wD_6QsP7JCQ&list=RDGMEMCMFH2exzjBeE_zAHHJOdxgVMd9n0uNjfTmI&index=2");
	google.getProfilePictureUrl();
	String url=google.getProfilePictureUrl();
	System.out.println(url);
	google.setUnreadEmails(143);
	google.getUnreadEmails();
	int unreadEmails=google.getUnreadEmails();
	System.out.println(unreadEmails);
	google.setEmailNotificationsEnabled(true);
	google.isEmailNotificationsEnabled();
	boolean Email=google.isEmailNotificationsEnabled();
	System.out.println(Email);
	google.setCalendarEvents("september");
	google.getCalendarEvents();
	String calendar=google.getCalendarEvents();
	System.out.println(calendar);
	google.setCalendarNotificationsEnabled(false);
	google.isCalendarNotificationsEnabled();
	boolean calendarNotification=google.isCalendarNotificationsEnabled();
	System.out.println(calendarNotification);
	google.setDriveStorageUsed(200);
	google.getDriveStorageUsed();
	int storage=google.getDriveStorageUsed();
	System.out.println(storage);
	google.setRecentFiles("java");
	google.getRecentFiles();
	String recentFiles=google.getRecentFiles();
	System.out.println(recentFiles);
	google.setDriveNotificationsEnabled(true);
	google.isDriveNotificationsEnabled();
	boolean driveStorage=google.isDriveNotificationsEnabled();
	System.out.println(driveStorage);
	google.setShoppingNotificationsEnabled(true);
	google.isShoppingNotificationsEnabled();
	boolean shopping=google.isShoppingNotificationsEnabled();
	System.out.println(shopping);
	google.setFinanceNotificationsEnabled(true);
	google.isFinanceNotificationsEnabled();
	boolean financeNotification=google.isFinanceNotificationsEnabled();
	System.out.println(financeNotification);
	google.setSportsNotificationsEnabled(true);
	google.isSportsNotificationsEnabled();
	boolean sports=google.isShoppingNotificationsEnabled();
	System.out.println(sports);
	google.setEntertainmentNotificationsEnabled(true);
	google.isEntertainmentNotificationsEnabled();
	boolean entertainment=google.isEntertainmentNotificationsEnabled();
	System.out.println(entertainment);
	google.setHealthNotificationsEnabled(true);
	google.isHealthNotificationsEnabled();
	boolean health=google.isHealthNotificationsEnabled();
	System.out.println(health);
	google.setStockNotificationsEnabled(true);
	google.isStockNotificationsEnabled();
	boolean stock=google.isStockNotificationsEnabled();
	System.out.println(stock);
	google.setMapHistoryEnabled(true);
	google.isMapHistoryEnabled();
	boolean map=google.isMapHistoryEnabled();
	System.out.println(map);
	google.setSavedPlaces("Bangloor");
	google.getSavedPlaces();
	String place=google.getSavedPlaces();
	System.out.println(place);
	google.setRecentSearches("place");
	google.getRecentSearches();
	String search= google.getRecentSearches();
	System.out.println(search);
	google.setMapNotificationsEnabled(true);
	google.isMapNotificationsEnabled();
	boolean Notification= google.isMapNotificationsEnabled();
	System.out.println( Notification);
	google.setYouTubeVideosUploaded(100);
	google.getYouTubeVideosUploaded();
	int youTubeVideosUploaded=google.getYouTubeVideosUploaded();
	System.out.println(youTubeVideosUploaded);
	google.setYouTubeSubscribers(200);
	google.getYouTubeSubscribers();
	int youtubeSubscribers=google.getYouTubeSubscribers();
	System.out.println(youtubeSubscribers);
	google.setYouTubeNotificationsEnabled(true);
	boolean YoutubeNotification=google.isYouTubeNotificationsEnabled();
	System.out.println(YoutubeNotification);
	google.getPhotosUploaded();
	google.setPhotosUploaded(300);
	int uploaded=google.getPhotosUploaded();
	System.out.println(uploaded);
    google.setPhotoNotificationsEnabled(true);
    google.isPhotoNotificationsEnabled();
    boolean photo=google.isPhotoNotificationsEnabled();
	System.out.println(photo);
	google.setContactsCount(200);
	google.getContactsCount();
	int contact=google.getContactsCount();
	System.out.println(contact);
	google.setContactSyncEnabled(false);
	google.isContactSyncEnabled();
	boolean contactSync=google.isContactSyncEnabled();
	System.out.println(contactSync);
	google.setBrowserHistoryCount(122);
	google.getBrowserHistoryCount();
	int browser=google.getBookmarksCount();
	System.out.println(browser);
	google.setLanguage("telugu");
	google.getLanguage();
	String languages=google.getLanguage();
	System.out.println(languages);
	google.setCurrency("Dollar");
	google.getCurrency();
	String currency=google.getCurrency();
	System.out.println(currency);
	google.setAutoCompleteEnabled(true);
	google.isAutoCompleteEnabled();
	boolean auto=google.isAutoCompleteEnabled();
	System.out.println(auto);
	google.setDarkModeEnabled(true);
	google.isDarkModeEnabled();
	boolean dark=google.isDarkModeEnabled();
	System.out.println(dark);
}
}
